import { SystemState } from '@/models/reduxmodel';
import { createSlice } from '@reduxjs/toolkit';

// Define the initial state for the slice
const initialState: SystemState = {
    userId: '',
    driverLat: 0,
    driverLng: 0,
    currentOrder: null
};

// Create the slice
const systemSlice = createSlice({
    name: 'system',
    initialState,
    reducers: {
        login: (state, action) => {
            state.userId = action.payload.userId;
        },
        logout: (state) => {
            state.userId = '';
        },
        addOrder: (state, action) => {
            state.currentOrder = action.payload.order;
        },
        updateDriverLocation: (state, action) => {
            state.driverLat = action.payload.driverLat;
            state.driverLng = action.payload.driverLng;
        },
    },
});

// Export the actions generated by createSlice
export const { login, logout, addOrder, updateDriverLocation } = systemSlice.actions;

// Export the reducer
export default systemSlice.reducer;