import { createSlice } from '@reduxjs/toolkit';

// Define the initial state for the slice
const initialState = {
    user: ''
};

// Create the slice
const systemSlice = createSlice({
    name: 'system',
    initialState,
    reducers: {
        // Reducer to handle a successful login
        login: (state, action) => {
            state.user = action.payload.user;
        },
        // Reducer to handle a logout
        logout: (state) => {
            state.user = '';
        },
    },
});

// Export the actions generated by createSlice
export const { login, logout } = systemSlice.actions;

// Export the reducer
export default systemSlice.reducer;