import { SystemState } from '@/models/reduxmodel';
import { createSlice } from '@reduxjs/toolkit';

// Define the initial state for the slice
const initialState: SystemState = {
    userId: '',
    driverLat: null,
    driverLng: null,
    currentOrder: null,
    workstatus: false
};

// Create the slice
const systemSlice = createSlice({
    name: 'system',
    initialState,
    reducers: {
        login: (state, action) => {
            state.userId = action.payload.userId;
        },
        logout: (state) => {
            state.userId = '';
        },
        addOrder: (state, action) => {
            state.currentOrder = action.payload.order;
        },
        clearOrder: (state, action) => {
            state.currentOrder = null;
        },
        updateWorkStatus: (state, action) => {
            state.workstatus = action.payload.workstatus;
        },
        updateDriverLocation: (state, action) => {
            state.driverLat = action.payload.driverLat;
            state.driverLng = action.payload.driverLng;
        },
    },
});

// Export the actions generated by createSlice
export const { login, logout, addOrder, updateDriverLocation, clearOrder, updateWorkStatus } = systemSlice.actions;

// Export the reducer
export default systemSlice.reducer;